FROM docker.n8n.io/n8nio/n8n

USER root

# Установка Python 3 и pip
RUN apk add --no-cache python3 py3-pip

# Опционально: установка дополнительных Python библиотек
# RUN pip3 install requests beautifulsoup4 pandas

USER node
